### ISSUE TITLE
Object Detection ...

### ISSUE THREAD

**Issue by MyVanitar** [humphd/have-fun-with-machine-learning#1]
Hello,

First I should appreciate your tutorial.

My question is if we decided to detect objects in photos (draw rectangle on detected objects and get the coordinate of the center) what we should do?

and second, ho we can have video as input from the camera? (such as HDMi camera)

**Comment by humphd** [comment]
Glad you like it, thanks.

I've never played with object detection, but I am aware of this example that discusses it: https://github.com/NVIDIA/DIGITS/tree/master/examples/object-detection.

Working with video frames is what I'm interested in as well, and I'm doing it in Python using `cv2.VideoCapture()` and then reading each frame with `.read()` and passing that into the network instead of a single image.  See https://github.com/alexgkendall/SegNet-Tutorial/blob/master/Scripts/webcam_demo.py for an example of this.

**Comment by MyVanitar** [comment]
Thanks for the reply.
So as I assume, for the object detection, at least till the training stage would be the same, and only difference would be how to use the trained model, isn't it?

**Comment by MyVanitar** [comment]
Please make another tutorial for object detection with Fine tuning method. I will so appreciate.
besides, after training how can we use our trained model to make standalone applications?

**Comment by humphd** [comment]
I've added a section and sample code for using the trained model in Python, see https://github.com/humphd/have-fun-with-machine-learning#python-example.

Doing an image detection example is a neat idea, but not something I'll be doing soon.  I'm going to close this.
