### ISSUE TITLE
No "Pretrained Models" tab | "processing" and "segmentation" do not show up within drop-down list

### ISSUE THREAD

**Issue by MyVanitar** [humphd/have-fun-with-machine-learning#2]
Hello,

I followed everything and installed Caffe and Digits, but my Digits GUI is a bit different with yours. I mean there is no "Pretrained Models" and "processing" tab, and "segmentation" do not show up within drop-down list.

Why it should be like this?!

**Comment by humphd** [comment]
Did you use a released version of DIGITS?  Likely that's the difference in UI, since I grabbed DIGITS from their Github repo, and I'm using the following commit (which is what `master` was at when I pulled): https://github.com/humphd/DIGITS/commit/81be5131821ade454eb47352477015d7c09753d9.  In the web app, if I go to `Info` in the top header, I see `DIGITS version: 5.1-dev`.

**Comment by humphd** [comment]
Thanks for alerting me to this, I've added notes in the README about which commits I used.

**Comment by MyVanitar** [comment]
yes, mine is 4.0

**Comment by yaniveliash** [comment]
Having same issue with Digits 4.0.0
